"""Another 3

Revision ID: 00f277780e0d
Revises: a416f025866e
Create Date: 2023-05-16 11:07:20.582676

"""
from alembic import op
import sqlalchemy as sa
from app import app, db

# revision identifiers, used by Alembic.
revision = '00f277780e0d'
down_revision = 'a416f025866e'
branch_labels = None
depends_on = None


def upgrade():
    class School(db.Model):
        school_id = db.Column(db.Integer, primary_key=True)
        eoname = db.Column(db.Text, unique=False)
        eotypename = db.Column(db.Text, unique=False)
        eoregname = db.Column(db.Text, unique=False)
        eoareaname = db.Column(db.Text, unique=False)
        eotername = db.Column(db.Text, unique=False)
        eoparent = db.Column(db.Text, unique=False)











    db.create_all()
    db.session.commit()





def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('god2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='god2_pkey'),
    sa.UniqueConstraint('email', name='god2_email_key')
    )
    op.create_table('god',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='god_pkey'),
    sa.UniqueConstraint('email', name='god_email_key')
    )
    op.create_table('user2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user2_pkey'),
    sa.UniqueConstraint('name', name='user2_name_key')
    )
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('birth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sextype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('areaname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tername', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('regtypename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tertypename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classprofilename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('classlangname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('name', name='user_name_key')
    )
    op.create_table('user1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user1_pkey'),
    sa.UniqueConstraint('email', name='user1_email_key'),
    sa.UniqueConstraint('name', name='user1_name_key')
    )
    # ### end Alembic commands ###
